# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewCourseBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewCourseBook
  pod 'RealmSwift', '2.9.0'

end
